# Generated by Django 4.2.5 on 2023-09-06 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=125)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('CSE', 'CSE'), ('ME', 'ME'), ('ECE', 'ECE')], default='MCA', max_length=50)),
                ('position', models.CharField(choices=[('Assiosite Profeser', 'Assiosite Profeser'), ('Lab Assiestent', 'Lab Assiestent'), ('HOD', 'HOD')], default='Assiosite Profeser', max_length=50)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
