# Generated by Django 4.2.5 on 2023-09-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('registrationNum', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('CSE', 'CSE'), ('ME', 'ME'), ('ECE', 'ECE')], default='MCA', max_length=50)),
                ('pursing_sem', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default='1st', max_length=50)),
                ('student_type', models.CharField(choices=[('Regular', 'Regular'), ('Distance', 'Distance')], default='Regular', max_length=25)),
                ('hosteller', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
