# Generated by Django 4.2.5 on 2023-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_studentsmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='registractionNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
