# Generated by Django 4.2.5 on 2023-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_teacher_subject_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('CSE', 'CSE'), ('EE', 'EE'), ('ECE', 'ECE')], default='Department', max_length=50),
        ),
    ]
