# Generated by Django 4.2.5 on 2023-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0007_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('sub1', 'Python (MCA)'), ('sub2', 'Java (MCA)'), ('DAA (MCA)', 'DAA (MCA)'), ('COA (MCA)', 'COA (MCA)'), ('C Programming (BCA)', 'C Programming (BCA)'), ('Digital Electronics (BCA)', 'Digital Electronics (BCA)'), ('Artificial Intelligence (BCA)', 'Artificial Intelligence (BCA)'), ('Artificial Intelligence (CSE)', 'Artificial Intelligence (CSE)'), ('Machine Learning (CSE)', 'Machine Learning (CSE)'), ('Electric Circuit Theory (EE)', 'Electric Circuit Theory (EE)'), ('Digital Electronics (EE)', 'Digital Electronics (EE)'), ('Power Electronics (EE)', 'Power Electronics (EE)'), ('Electronic Devices (ECE)', 'Electronic Devices (ECE)'), ('Analog Communication (ECE)', 'Analog Communication (ECE)'), ('Microprocessor & Microcontrollers (ECE)', 'Microprocessor & Microcontrollers (ECE)')], default='Subject', max_length=50),
        ),
    ]
