# Generated by Django 4.2.5 on 2023-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0008_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmarks',
            name='marks',
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='addicational',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='subject1',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='subject2',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='subject3',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('sub1', 'Python (MCA)'), ('sub2', 'Java (MCA)'), ('sub3', 'DAA (MCA)'), ('sub4', 'COA (MCA)'), ('sub1', 'C Programming (BCA)'), ('sub2', 'Digital Electronics (BCA)'), ('sub3', 'Artificial Intelligence (BCA)'), ('sub1', 'Artificial Intelligence (CSE)'), ('sub2', 'Machine Learning (CSE)'), ('sub3', 'Compiler Design (CSE)'), ('sub1', 'Electric Circuit Theory (EE)'), ('sub2', 'Digital Electronics (EE)'), ('sub3', 'Power Electronics (EE)'), ('sub1', 'Electronic Devices (ECE)'), ('sub2', 'Analog Communication (ECE)'), ('sub3', 'Microprocessor & Microcontrollers (ECE)')], default='Subject', max_length=50),
        ),
    ]
