# Generated by Django 4.2.5 on 2023-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0010_alter_studentsmarks_registractionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='subject1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='subject2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='subject3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
