# Generated by Django 4.2.5 on 2023-09-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0011_alter_studentsmarks_subject1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MCA', 'MCA')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admitDate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hosteller',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pursing_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registrationNum',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='registractionNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('COA', 'COA'), ('DBMS', 'DBMS'), ('ML', 'ML'), ('AI', 'AI')], max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.semester')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='semesters_enrolled',
            field=models.ManyToManyField(to='TestApp.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='TestApp.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='semester_taught',
            field=models.ManyToManyField(to='TestApp.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.department'),
        ),
    ]
