# Generated by Django 4.2.5 on 2023-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0013_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
