# Generated by Django 4.2.5 on 2023-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0014_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('MCA', 'Master of Computer Applications'), ('BCA', 'Bachelor of Computer Applications')], default='Select Department', max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')], default='Select Semester', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Select Subject', max_length=50),
        ),
    ]
