# Generated by Django 4.2.5 on 2023-09-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0015_alter_department_name_alter_semester_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentsmarks',
            table='Marks',
        ),
    ]
