# Generated by Django 4.2.5 on 2023-09-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0017_teacher_subject_taught_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('COA', 'COA'), ('Discrete Mathematics', 'Discrete Mathematics'), ('DBMS', 'Database Management System'), ('Data Structure', 'Data Structure'), ('Java', 'Java'), ('Operating System', 'Operation System'), ('Networking', 'Networking'), ('Computer Graphics', 'computer Graphics'), ('DAA', 'Design and Analysis of algorithms'), ('Software engineering', 'Software engineering'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('DS', 'Basic Data Science')], default='Select Subject', max_length=50),
        ),
    ]
