# Generated by Django 4.2.5 on 2023-09-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0018_student_rejected_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_recode', models.DateField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.teacher')),
            ],
        ),
    ]
