# Generated by Django 4.2.5 on 2023-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0019_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
