# Generated by Django 4.2.5 on 2023-09-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0020_alter_mark_marks_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.teacher')),
            ],
        ),
    ]
