# Generated by Django 4.2.5 on 2023-10-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0021_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rejected',
        ),
    ]
