# Generated by Django 4.2.5 on 2023-10-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0023_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TestApp.semester'),
        ),
    ]
