# Generated by Django 4.2.5 on 2023-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0024_announcement_department_announcement_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='notices/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
