# Generated by Django 4.2.5 on 2023-10-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0025_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(),
        ),
    ]
